name: 'Setup Node.js environment'
description: 'Setup Node.js and install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version-file: 'package.json'
    - name: 'Cache node_modules'
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: 'Install Node.js dependencies'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci --prefer-offline --no-audit --no-fund
      shell: bash
