export const PROVIDERS = [
  {
    value: 'Ollama',
    name: 'Ollama',
    base_url: null,
  },
  {
    value: 'Anthropic',
    name: 'Anthropic',
    base_url: 'https://api.anthropic.com',
  },
  {
    value: 'OpenAI',
    name: 'OpenAI',
    base_url: 'https://api.openai.com',
  },
  {
    value: 'HuggingFace',
    name: 'Hugging Face',
    base_url: 'https://api-inference.huggingface.co',
  },
  {
    value: 'Mistral',
    name: 'Mistral',
    base_url: 'https://api.mistral.ai',
  },
  {
    value: 'OvhAiEndpoints',
    name: 'OVHcloud AI Endpoints',
    base_url: 'https://model_name.endpoints.kepler.ai.cloud.ovh.net',
  },
  {
    value: 'Scaleway',
    name: 'Scaleway Generative APIs',
    base_url: 'https://api.scaleway.ai',
  },
  {
    value: 'AzureOpenAi',
    name: 'Azure OpenAI',
    base_url: null,
  },
  {
    value: 'Groq',
    name: 'GroqCloud',
    base_url: 'https://api.groq.com',
  },
  {
    value: 'Cloudflare',
    name: 'Cloudflare Workers AI',
    base_url: null,
  },
  {
    value: 'Cohere',
    name: 'Cohere',
    base_url: 'https://api.cohere.com',
  },
  {
    value: 'Gemini',
    name: 'Google Gemini',
    base_url: 'https://generativelanguage.googleapis.com/v1beta',
  },
  {
    value: 'XAi',
    name: 'xAI',
    base_url: 'https://api.x.ai',
  },
];

export const OVHAIENDPOINTS_MODELS = {
  updateDate: '2024-12-01',
  models: [
    {
      id: 'f489186d-fc78-4244-bf0c-c8d67fda43e5',
      name: 'roberta-base-go_emotions',
      version: 'v1.0',
      description: 'This RoBERTa base model has been pretrained to extract emotions from text.',
      available: true,
      documentation_url: 'https://roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        languages: [
          'en',
        ],
        licence: 'MIT',
        source: 'https://huggingface.co/SamLowe/roberta-base-go_emotions',
      },
      created_at: '2024-04-17T12:27:08.832423+00:00',
      updated_at: '2024-04-17T12:27:08.832423+00:00',
      category: 'Natural Language Processing',
      tags: [
        'Emotion Extraction',
      ],
      openapi_url: 'https://roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'f3d108ed-b15a-4234-aeed-7f03516c942e',
      name: 'Llama-3-8B-Instruct',
      version: 'v1.0',
      description: 'Llama 3 (8 billion parameters version) is the smallest LLM of the Llama 3 collection. Llama 3 models are auto-regressive language models that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.\r\nBuilt with Meta Llama 3',
      available: true,
      documentation_url: 'https://llama-3-8b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://llama-3-8b-instruct.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://llama-3-8b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-05-17T07:48:32.85672+00:00',
      updated_at: '2024-05-17T07:48:32.85672+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://llama-3-8b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'ee061241-38a9-4d5c-868e-ddf00d098c22',
      name: 'bert-base-NER',
      version: 'v1.0',
      description: 'This Bert base model has been pretrained to recognize entities from text.',
      available: true,
      documentation_url: 'https://bert-base-ner.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://bert-base-ner.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://bert-base-ner.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        languages: [
          'en',
        ],
        licence: 'MIT',
        source: 'https://huggingface.co/dslim/bert-base-NER',
      },
      created_at: '2024-04-17T12:24:21.655646+00:00',
      updated_at: '2024-04-17T12:24:21.655646+00:00',
      category: 'Natural Language Processing',
      tags: [
        'Name Entity Recognition',
      ],
      openapi_url: 'https://bert-base-ner.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'eaa91559-af12-44a9-93d3-d8e99adf5811',
      name: 'nvr-nmt-en-zh',
      version: 'v1.0',
      description: 'Neural Machine Translation (NMT) models translate text from one language to another.',
      available: true,
      documentation_url: 'https://nvr-nmt-en-zh.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-nmt-en-zh.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:25:09.795117+00:00',
      updated_at: '2024-06-25T09:25:09.795117+00:00',
      category: 'Translation',
      tags: [],
      openapi_url: 'https://nvr-nmt-en-zh.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'e57e9c22-5c55-4277-ae05-9d5d1d0f9c3f',
      name: 'Llama-3-70B-Instruct',
      version: 'v1.0',
      description: 'Llama 3 (70 billion parameters version) is the biggest LLM of the Llama 3 collection. Llama 3 models are auto-regressive language models that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.\r\nBuilt with Meta Llama 3',
      available: true,
      documentation_url: 'https://llama-3-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://llama-3-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://llama-3-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-05-17T07:51:08.733058+00:00',
      updated_at: '2024-05-17T07:51:08.733058+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://llama-3-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'e2ecb4a7-98d5-420d-9789-e0aa6ddf0ffc',
      name: 'Mixtral-8x7b-instruct',
      version: 'v0.1',
      description: 'Mixtral-8x7B-Instruct-v0.1 Large Language Model (LLM) is a pretrained generative Sparse Mixture of Experts.',
      available: true,
      documentation_url: 'https://mixtral-8x7b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mixtral-8x7b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://mixtral-8x7b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '32k',
      },
      created_at: '2024-04-11T14:41:35.880979+00:00',
      updated_at: '2024-04-11T14:41:35.880979+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://mixtral-8x7b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'da728a25-bcb9-42ba-b8c0-1df3c4c42bd4',
      name: 'nvr-tts-es-es',
      version: 'v1.0',
      description: 'TTS system enables you to synthesize natural speech from raw transcriptions without any additional information.',
      available: true,
      documentation_url: 'https://nvr-tts-es-es.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-tts-es-es.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:51:07.539289+00:00',
      updated_at: '2024-06-25T09:51:07.539289+00:00',
      category: 'Audio Analysis',
      tags: [
        'Text To Speech',
      ],
      openapi_url: 'https://nvr-tts-es-es.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'd1b4ce86-6a0a-498d-990a-0f0f504fa97c',
      name: 'nvr-tts-de-de',
      version: 'v1.0',
      description: 'TTS system enables you to synthesize natural speech from raw transcriptions without any additional information.',
      available: true,
      documentation_url: 'https://nvr-tts-de-de.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-tts-de-de.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:50:22.737475+00:00',
      updated_at: '2024-06-25T09:50:22.737475+00:00',
      category: 'Audio Analysis',
      tags: [
        'Text To Speech',
      ],
      openapi_url: 'https://nvr-tts-de-de.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'c562636a-27b4-436c-be6a-3c70b9c249db',
      name: 'Mathstral-7B-v0.1',
      version: 'v1.0',
      description: ' Mathstral 7B is a model specializing in mathematical and scientific tasks, based on Mistral 7B',
      available: true,
      documentation_url: 'https://mathstral-7b-v01.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mathstral-7b-v01.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://mathstral-7b-v01.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '32k',
      },
      created_at: '2024-10-01T08:29:28.118953+00:00',
      updated_at: '2024-10-01T08:29:28.118953+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://mathstral-7b-v01.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: 'c504be89-f05d-4c65-b491-561996a4d179',
      name: 'mamba-codestral-7b-v0-1',
      version: 'v1.0',
      description: 'Codestral Mamba is an open code model based on the Mamba2 architecture',
      available: true,
      documentation_url: 'https://mamba-codestral-7b-v0-1.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mamba-codestral-7b-v0-1.endpoints.kepler.ai.cloud.ovh.net',
      licence_url: 'https://mamba-codestral-7b-v0-1.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '4k',
      },
      created_at: '2024-10-25T12:29:56.164852+00:00',
      updated_at: '2024-10-25T12:29:56.164852+00:00',
      category: 'Assistant',
      tags: [
        'Code Assistant',
      ],
      openapi_url: 'https://mamba-codestral-7b-v0-1.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: 'c390a155-ad79-46ee-ba73-bf614010f779',
      name: 'nvr-tts-zh-cn',
      version: 'v1.0',
      description: 'TTS system enables you to synthesize natural speech from raw transcriptions without any additional information.',
      available: true,
      documentation_url: 'https://nvr-tts-zh-cn.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-tts-zh-cn.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:53:10.920616+00:00',
      updated_at: '2024-06-25T09:53:10.920616+00:00',
      category: 'Audio Analysis',
      tags: [
        'Text To Speech',
      ],
      openapi_url: 'https://nvr-tts-zh-cn.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'c342c22d-a00f-4144-b2dd-5dfd31d98b01',
      name: 'Mistral-7B-Instruct',
      version: 'v0.2',
      description: 'Mistral-7B-Instruct-v0.2 Large Language Model (LLM) is a pretrained generative text model with 7 billion parameters.',
      available: true,
      documentation_url: 'https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '32k',
      },
      created_at: '2024-04-17T12:38:39.112715+00:00',
      updated_at: '2024-04-17T12:38:39.112715+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'bdc6854c-9aac-40a3-bde7-a8fb0bbdc02f',
      name: 'bart-large-cnn',
      version: 'v1.0',
      description: 'This Bart large model is a pretrained text summarization model.',
      available: true,
      documentation_url: 'https://bart-large-cnn.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://bart-large-cnn.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://bart-large-cnn.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        languages: [
          'en',
        ],
        licence: 'MIT',
        source: 'https://huggingface.co/facebook/bart-large-cnn',
      },
      created_at: '2024-04-17T10:25:24.36293+00:00',
      updated_at: '2024-04-17T10:25:24.36293+00:00',
      category: 'Natural Language Processing',
      tags: [],
      openapi_url: 'https://bart-large-cnn.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'bb180ee1-36c7-4f60-b432-639fc6ea58df',
      name: 'multilingual-e5-base',
      version: 'v1.0',
      description: 'Multilingual embedding model for computing sentence similarity',
      available: true,
      documentation_url: 'https://multilingual-e5-base.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://multilingual-e5-base.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://multilingual-e5-base.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-04-30T14:20:38.443275+00:00',
      updated_at: '2024-04-30T14:20:38.443275+00:00',
      category: 'Embeddings',
      tags: [],
      openapi_url: 'https://multilingual-e5-base.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'b8c9dcfc-e8cd-43b2-acf4-075a6a8ef1c1',
      name: 'nvr-asr-es-us',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-es-us.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-es-us.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:42:20.684099+00:00',
      updated_at: '2024-06-25T09:42:20.684099+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-es-us.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'b83ff1e3-cc0b-4375-bc5d-f4304b46915e',
      name: 'nvr-asr-es-es',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-es-es.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-es-es.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:41:16.17284+00:00',
      updated_at: '2024-06-25T09:41:16.17284+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-es-es.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'b74834fe-8f1c-4b40-a525-24be45089649',
      name: 'nvr-nmt-en-es',
      version: 'v1.0',
      description: 'Neural Machine Translation (NMT) models translate text from one language to another.',
      available: true,
      documentation_url: 'https://nvr-nmt-en-es.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-nmt-en-es.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T08:15:43.34243+00:00',
      updated_at: '2024-06-25T08:15:43.34243+00:00',
      category: 'Translation',
      tags: [],
      openapi_url: 'https://nvr-nmt-en-es.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'b64853da-8f3c-42a2-8fe4-363e97dfd045',
      name: 'nvr-asr-zh-cn',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-zh-cn.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-zh-cn.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:44:07.144622+00:00',
      updated_at: '2024-06-25T09:44:07.144622+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-zh-cn.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: 'b1cf82d0-4975-40b2-b2a4-e7d9b33ac7f4',
      name: 'yolov11x_image_segmentation',
      version: 'v1.0',
      description: 'This YOLO model has been pretrained to segment various objects in images.',
      available: false,
      documentation_url: 'https://samlowe-roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net',
      gradio_url: 'https://samlowe-roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/app',
      licence_url: 'https://samlowe-roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-04-17T12:29:08.777922+00:00',
      updated_at: '2024-04-17T12:29:08.777922+00:00',
      category: 'Computer vision',
      tags: [
        'Image Segmentation',
      ],
      openapi_url: 'https://samlowe-roberta-base-go-emotions.endpoints.kepler.ai.cloud.ovh.net/doc',
      new: false,
      isNew: false,
    },
    {
      id: 'a4f3a9fd-c73f-4572-954f-86ec18ebf567',
      name: 'Llama-3.1-70B-Instruct',
      version: 'v1.0',
      description: ' Llama 3.1 (70B parameters version) is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.',
      available: true,
      documentation_url: 'https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '128k',
      },
      created_at: '2024-10-01T07:53:58.816946+00:00',
      updated_at: '2024-10-01T07:53:58.816946+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: 'a363a190-ff7b-4c38-a1b9-147f9aae9328',
      name: 'stable-diffusion-xl',
      version: 'v1.0',
      description: 'This is a model that can be used to generate images based on text prompts. It is a Latent Diffusion Model.',
      available: true,
      documentation_url: 'https://stable-diffusion-xl.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://stable-diffusion-xl.endpoints.kepler.ai.cloud.ovh.net',
      licence_url: 'https://stable-diffusion-xl.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-10-30T14:13:19.098586+00:00',
      updated_at: '2024-10-30T14:13:19.098586+00:00',
      category: 'Image Generation',
      tags: [
        'Image Generation',
      ],
      openapi_url: 'https://stable-diffusion-xl.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: 'a0f77c47-1d6f-42ee-938d-dd4dee4ffbe1',
      name: 'BGE-M3',
      version: 'v1.0',
      description: 'Multilingual, multifunctional and multigranular embedding model',
      available: true,
      documentation_url: 'https://bge-m3.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://bge-m3.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://bge-m3.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-11-18T15:34:10.785341+00:00',
      updated_at: '2024-11-18T15:34:10.785341+00:00',
      category: 'Embeddings',
      tags: [],
      openapi_url: 'https://bge-m3.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: '9c151ec9-32f5-450a-9511-7bccfb3235e9',
      name: 'Mistral-Nemo-Instruct-2407',
      version: 'v0.1',
      description: 'Mistral-Nemo-Instruct-2407 is a Large Language Model (LLM) trained jointly by Mistral AI and NVIDIA.',
      available: true,
      documentation_url: 'https://mistral-nemo-instruct-2407.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mistral-nemo-instruct-2407.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://mistral-nemo-instruct-2407.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-11-21T16:33:52.197639+00:00',
      updated_at: '2024-11-21T16:33:52.197639+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://mistral-nemo-instruct-2407.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: '97970ff4-0a17-40e6-98d9-e1a3e11124bb',
      name: 'Llama-2-13b-chat-hf',
      version: 'v1.0',
      description: 'Llama 2, 13B version, is a pretrained and fine-tuned generative text model of 13 billion parameters. This "chat" version is optimized for dialogue use cases.',
      available: true,
      documentation_url: 'https://llama-2-13b-chat-hf.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://llama-2-13b-chat-hf.endpoints.kepler.ai.cloud.ovh.net',
      licence_url: 'https://llama-2-13b-chat-hf.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '4k',
      },
      created_at: '2024-04-17T12:35:30.95894+00:00',
      updated_at: '2024-04-17T12:35:30.95894+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://llama-2-13b-chat-hf.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '957e48e8-4163-4554-b697-ebdd5b96e647',
      name: 'yolov11x_object_detection',
      version: 'v1.0',
      description: 'This YOLO model has been pretrained to recognize and classify objects of a certain class in images.',
      available: true,
      documentation_url: 'https://yolov11x-object-detection.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://yolov11x-object-detection.endpoints.kepler.ai.cloud.ovh.net',
      licence_url: 'https://yolov11x-object-detection.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-04-17T12:30:12.181069+00:00',
      updated_at: '2024-04-17T12:30:12.181069+00:00',
      category: 'Computer vision',
      tags: [],
      openapi_url: 'https://yolov11x-object-detection.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: true,
      isNew: true,
    },
    {
      id: '8a5b5994-3862-4465-a947-0893024b2dfd',
      name: 'nvr-asr-de-de',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-de-de.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-de-de.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:37:29.478545+00:00',
      updated_at: '2024-06-25T09:37:29.478545+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-de-de.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '610fffb6-026f-4c29-bc4a-9f3dfa80994c',
      name: 'nvr-asr-fr-fr',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-fr-fr.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-fr-fr.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-17T09:00:57.046227+00:00',
      updated_at: '2024-06-17T09:00:57.046227+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-fr-fr.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '5f607d54-57fa-46ff-b243-87856a242aa0',
      name: 'nvr-tts-en-us',
      version: 'v1.0',
      description: 'TTS system enables you to synthesize natural speech from raw transcriptions without any additional information.',
      available: true,
      documentation_url: 'https://nvr-tts-en-us.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-tts-en-us.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-17T08:47:24.456767+00:00',
      updated_at: '2024-06-17T08:47:24.456767+00:00',
      category: 'Audio Analysis',
      tags: [
        'Text To Speech',
      ],
      openapi_url: 'https://nvr-tts-en-us.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '5eee37d6-7662-4667-908d-aaaf26e722cc',
      name: 'nvr-tts-it-it',
      version: 'v1.0',
      description: 'TTS system enables you to synthesize natural speech from raw transcriptions without any additional information.',
      available: true,
      documentation_url: 'https://nvr-tts-it-it.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-tts-it-it.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:52:02.830814+00:00',
      updated_at: '2024-06-25T09:52:02.830814+00:00',
      category: 'Audio Analysis',
      tags: [
        'Text To Speech',
      ],
      openapi_url: 'https://nvr-tts-it-it.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '4ed6f10b-58b9-4bce-a9a8-05a17e5a8d71',
      name: 'nvr-asr-it-it',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-it-it.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-it-it.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:43:17.04659+00:00',
      updated_at: '2024-06-25T09:43:17.04659+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-it-it.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '30da93c6-f951-43d0-bb9b-ea6e75354af4',
      name: 'nvr-asr-en-gb',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-en-gb.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-en-gb.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-04-17T12:31:09.416441+00:00',
      updated_at: '2024-04-17T12:31:09.416441+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-en-gb.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '2d9085b1-d68d-4465-8722-c502287f4c4b',
      name: 'bge-base-en-v1.5',
      version: 'v1.0',
      description: 'English embedding model for computing sentence similarity',
      available: true,
      documentation_url: 'https://bge-base-en-v1-5.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://bge-base-en-v1-5.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://bge-base-en-v1-5.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {},
      created_at: '2024-04-30T14:16:26.68998+00:00',
      updated_at: '2024-04-30T14:16:26.68998+00:00',
      category: 'Embeddings',
      tags: [],
      openapi_url: 'https://bge-base-en-v1-5.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '2577dd9b-df41-4e56-80d6-e998a07409a9',
      name: 'nvr-nmt-en-de',
      version: 'v1.0',
      description: 'Neural Machine Translation (NMT) models translate text from one language to another.',
      available: true,
      documentation_url: 'https://nvr-nmt-en-de.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-nmt-en-de.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:21:37.896889+00:00',
      updated_at: '2024-06-25T09:21:37.896889+00:00',
      category: 'Translation',
      tags: [],
      openapi_url: 'https://nvr-nmt-en-de.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '23600fb3-7b3e-4d39-823c-7d66b8203e24',
      name: 'nvr-nmt-en-fr',
      version: 'v1.0',
      description: 'Neural Machine Translation (NMT) models translate text from one language to another.',
      available: true,
      documentation_url: 'https://nvr-nmt-en-fr.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-nmt-en-fr.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-17T08:56:42.027638+00:00',
      updated_at: '2024-06-17T08:56:42.027638+00:00',
      category: 'Translation',
      tags: [],
      openapi_url: 'https://nvr-nmt-en-fr.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '0d492510-e5e6-429b-bb1f-de8add9436ca',
      name: 'nvr-asr-en-us',
      version: 'v1.0',
      description: 'ASR model allows you to recognize and transcribe audio, especially human speech, into text.',
      available: true,
      documentation_url: 'https://nvr-asr-en-us.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://nvr-asr-en-us.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/',
      metadata: {},
      created_at: '2024-06-25T09:40:14.814584+00:00',
      updated_at: '2024-06-25T09:40:14.814584+00:00',
      category: 'Audio Analysis',
      tags: [
        'Automatic Speech Recognition',
      ],
      openapi_url: 'https://nvr-asr-en-us.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '0bcad2b7-ef6e-4f36-b8cf-14667485b032',
      name: 't5-large',
      version: 'v1.0',
      description: 'This T5 large model has been pretrained to translate English text to another language.',
      available: true,
      documentation_url: 'https://t5-large.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://t5-large.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://t5-large.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        languages: [
          'en',
          'fr',
          'de',
          'ro',
        ],
        licence: 'apache-2.0',
        source: 'https://huggingface.co/google-t5/t5-large',
      },
      created_at: '2024-04-17T12:28:07.18766+00:00',
      updated_at: '2024-04-17T12:28:07.18766+00:00',
      category: 'Translation',
      tags: [],
      openapi_url: 'https://t5-large.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '0798164c-4b61-43a7-bbfc-1add2285229a',
      name: 'CodeLlama-13b-Instruct-hf',
      version: 'v1.0',
      description: 'Code Llama is a pretrained and fine-tuned generative text models with 13 billion parameters. This model is designed for general code synthesis and understanding. ',
      available: true,
      documentation_url: 'https://codellama-13b-instruct-hf.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://codellama-13b-instruct-hf.endpoints.kepler.ai.cloud.ovh.net',
      licence_url: 'https://codellama-13b-instruct-hf.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '16k',
      },
      created_at: '2024-04-17T12:34:40.496122+00:00',
      updated_at: '2024-04-17T12:34:40.496122+00:00',
      category: 'Assistant',
      tags: [
        'Code Assistant',
      ],
      openapi_url: 'https://codellama-13b-instruct-hf.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '018a19ab-167f-473b-8ec5-acb44380d175',
      name: 'Mixtral-8x22b-Instruct',
      version: 'v1.0',
      description: 'The Mixtral-8x22B-Instruct Large Language Model (LLM) is a pretrained generative Sparse Mixture of Experts it has been fine tuned especially to follow instructions.',
      available: true,
      documentation_url: 'https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        context: '64k',
      },
      created_at: '2024-05-20T13:07:23.45836+00:00',
      updated_at: '2024-05-20T13:07:23.45836+00:00',
      category: 'Assistant',
      tags: [],
      openapi_url: 'https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
    {
      id: '012ee94d-2794-4ae6-b44a-0382ff34a7b6',
      name: 'bert-base-multilingual-uncased-sentiment',
      version: 'v1.0',
      description: 'This Bert base model has been pretrained to analyze sentiments from text.',
      available: true,
      documentation_url: 'https://bert-base-multilingual-uncased-sentiment.endpoints.kepler.ai.cloud.ovh.net/doc/readme',
      gradio_url: 'https://bert-base-multilingual-uncased-sentiment.endpoints.kepler.ai.cloud.ovh.net/',
      licence_url: 'https://bert-base-multilingual-uncased-sentiment.endpoints.kepler.ai.cloud.ovh.net/doc/license',
      metadata: {
        languages: [
          'en',
          'du',
          'de',
          'fr',
          'it',
          'es',
        ],
        licence: 'MIT',
        source: 'https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment',
      },
      created_at: '2024-04-17T12:26:09.568574+00:00',
      updated_at: '2024-04-17T12:26:09.568574+00:00',
      category: 'Natural Language Processing',
      tags: [
        'Sentiment Analysis',
      ],
      openapi_url: 'https://bert-base-multilingual-uncased-sentiment.endpoints.kepler.ai.cloud.ovh.net/doc/openapi.json',
      new: false,
      isNew: false,
    },
  ],
};
