name: 'Build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: '[Prepare] Install dependencies'
        run: npm ci

      - name: '[Code quality] Check commit message'
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: '[Code quality] Check ESLint'
        run: npm run lint

      - name: '[Build] [Prepare] Setup ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: '[Build] [Prepare] Install fpm'
        run: gem install fpm
      - name: '[Build] [Run] Build'
        run: node scripts/job-build.js 0.0.0 --latest --bundle
        env:
          RPM_GPG_PRIVATE_KEY: ${{ secrets.RPM_GPG_PRIVATE_KEY }}
          RPM_GPG_NAME: 'Clever Cloud Nexus (rpm)'
          RPM_GPG_PASS: ${{ secrets.RPM_GPG_PASSPHRASE }}
